### PR TITLE
Use max_throttling and add throughput

### PR DESCRIPTION
**Pull request by fengalin**
Update to use the proposed [draft version for tokio throttling](https://github.com/fengalin/tokio/tree/fengalin/throttling) and to display the throughput in this benchmark.

### CODE REVIEW

**Comment by fengalin** [comment]
There must be something wrong though because I don't get as good an improvement on CPU usage. Investigating...

**Comment by fengalin** [comment]
I get somewhat the same CPU usage improvement by [removing some code](https://github.com/fengalin/tokio/commit/d88d2843c6afef228adcbcfb07a57c9fcac7d4a4). However, that code was added in order to pass the following tests in `rt_common`:

- `complete_block_on_under_load`
- `complete_task_under_load`
- `io_driver_called_when_under_load`

So it seems like we don't cover all the intended use cases with this approach. I can adjust `MAX_TASKS_PER_TICK` to favor the `throttling`.

Do you see anything else I could improve? IMHO, upstream would not accept the changes with either versions.

**Comment by sdroege** [comment]
There's a fundamental problem with `MAX_TASKS_PER_TICK`. If you use this in combination with throttling then you will not run some tasks for some iterations if there are too many, and because we now throttle this means that tasks that would be ready are not handled.

I think this whole function needs to be implemented separately for the throttling and non-throttling case. For non-throttling the number of tasks limitation makes sense.

----

The part about the timers commented out is needed for keeping performance improvements?

----

What is `self.drain_pending_drop();` doing exactly and why is it important?

**Comment by fengalin** [comment]
I guess I just needed some rest... See [this version](https://github.com/fengalin/tokio/blob/fa6b212ec250e8420e8f3dab969f42ec7c04f19c/tokio/src/runtime/basic_scheduler.rs#L286) which passes all tests. With your benchmark, I get a better throughput and 30% less CPU usage than the non-throttling version.

Tell me if you think this is OK now. I'll try improving the overall integration in the existing code base.

----

`MAX_TASKS_PER_TICK` is also used to balance between a task not relying on I/O that is always yielding and a task relying on I/O (ex. `io_driver_called_when_under_load` in `rt_common`).

> I think this whole function needs to be implemented separately for the throttling and non-throttling case.

That's what I did. Moreover, for the throttling case I separated the `Driver` for the `timer` from the `Driver` for the I/O and kept the original approach for the non-throttling case (combined `Driver`s and same untouched `tick` algorithm).

> What is `self.drain_pending_drop();` doing exactly and why is it important?

It's removing completed tasks from the active queue.

Let me know if you need a better presentation of the approach I used.

**Comment by fengalin** [comment]
I'll also improve the approach by which I trigger the occasional "Maintenance work" and "Check I/O". I just wanted to show you something that I find promising.

**Comment by sdroege** [comment]
> I guess I just needed some rest... See [this version](https://github.com/fengalin/tokio/blob/fa6b212ec250e8420e8f3dab969f42ec7c04f19c/tokio/src/runtime/basic_scheduler.rs#L286) which passes all tests. With your benchmark, I get a better throughput and 30% less CPU usage than the non-throttling version.

Seems good to me :) Thanks!

**Comment by sdroege** [comment]
Isn't https://github.com/fengalin/tokio/blob/fa6b212ec250e8420e8f3dab969f42ec7c04f19c/tokio/src/runtime/basic_scheduler.rs#L367 waking up immediately if a timer is supposed to happen before the throttle time?

**Comment by fengalin** [comment]
Yes it does. I though about looping on this until the wait time is elapsed but didn't do it... Let me try this.

**Comment by fengalin** [comment]
Issue "fired timers cancelling throttling" fixed in [this commit](https://github.com/fengalin/tokio/commit/783d6c7ef215b03fe229326580d1da03deac696e).

I'll try improving the integration later today and squash + rebase on upstream master (note that rebasing will alter your initial commit). Is there any other improvement that you would think about before I submit this upstream?

**Comment by sdroege** [comment]
I'd have to read it in more detail but for starters it should be ok :) The proper timer throttling you'd do afterwards (making them know about the intervals so that they don't on average fire half an interval too late)?

**Comment by fengalin** [comment]
> The proper timer throttling you'd do afterwards (making them know about the intervals so that they don't on average fire half an interval too late)?

AFAICT, we don't have to do this here (I noticed this strategy in the `threadshare` code). The `local.park` checks for the next timer to be be fired before `park`ing and adapts accordingly. See in [`time::driver::park*`](https://github.com/fengalin/tokio/blob/783d6c7ef215b03fe229326580d1da03deac696e/tokio/src/time/driver/mod.rs#L247). Or did I missunderstand your question?

**Comment by fengalin** [comment]
Or do you mean we should also fire the tasks if a timer is fired? (Without checking I/o)

**Comment by sdroege** [comment]
> Or did I missunderstand your question?

I think so. Consider we're throttling with 20ms, and we have a timer scheduled at 1ms. We wouldn't trigger that at 0ms because it's too early, but we would trigger it at 20ms. That would be 19ms later than it was scheduled. Because of this you would always trigger timers on average throttle_time/2 later than they were scheduled.

The solution for that would be to check the next wakeup time, and then trigger the timer up to throttle_time/2 **too early**.

**Comment by fengalin** [comment]
Of course! We are only interested in throttling I/O. Since we can control all the task / time / I/O handling, it's just a matter of handling I/O only after certain deadline. The rest can operate like in the non-throttling mode, regardless of the I/O deadline. With this approach, we don't have to worry whether we need to trigger timers half a period in advance since we can fire tasks as soon as the timer is fired.

I [changed the implementation](https://github.com/fengalin/tokio/blob/22efb50b9f21e277139bc12eb0948ad8da73a361/tokio/src/runtime/basic_scheduler.rs#L288) based on this principle. Now, I get 12% increase in throughput for about 1/4 of the CPU usage of the non-throttling version! I'd like to double check this though, because it seems a bit too good to be true. I hope I didn't fall in the starvation issue you mentioned before.

Now, we could try adjusting `MAX_TASKS_PER_CYCLE`, but we would need another bench not just focused on I/O for this I guess.

**Comment by sdroege** [comment]
In case of e.g. the rtpjitterbuffer this would then cause timers to wake up all the time instead of having them also throttled :) The goal is to also throttle timers

**Comment by fengalin** [comment]
> The goal is to also throttle timers

I don't get it. Why do you want to throttle timers?

**Comment by sdroege** [comment]
> I don't get it. Why do you want to throttle timers?

With the jitterbuffer you receive a packet at time N. You would send it out at latest at time N+latency via timers. If we now schedule timers for each packet this means that we will wake up all the time again, causing lots of context switches etc, when using multiple instances at the same time as their times would be randomly distributed.

**Comment by fengalin** [comment]
So you want to throttle outgoing I/O, right?

**Comment by sdroege** [comment]
Also, but also processing in general.

**Comment by fengalin** [comment]
When I looked at the timer implementation in tokio, I had the 1/2 period thing in my mind, but it didn't seem to me that it would be easy to fit that in. I think I need to step back a little. I'll look at this later or tomorrow.

**Comment by sdroege** [comment]
No problem :) Thanks!

**Comment by fengalin** [comment]
I made a [new version](https://github.com/fengalin/tokio/commit/5644c0b782aa94df44bd165e561649bad7bf3c67) which hopefully takes care of all the cases we discussed above. I still need to write some specific tests and clean things up a bit. CPU usage is better than non-throttling version, but far less impressive than the version discussed in [this comment](https://github.com/sdroege/tokio-udp-receiver-benchmark/pull/1#issuecomment-563252013). We might be able to improve things a bit by adjusting the `MAX_TASKS_PER_TICK`, but like I said before, we should probably adapt the benchmark to use more tasks so that we don't mostly handle I/O.

I'll be away for one or two days, so I probably won't make much progress until Thursday. Could you check if the improvement is in-line with what you expected please?

**Comment by sdroege** [comment]
> Could you check if the improvement is in-line with what you expected please?

Sure, I'll take a look later :) Thanks a lot and enjoy your days off!

**Comment by sdroege** [comment]
> CPU usage is better than non-throttling version, but far less impressive than the version discussed in [this comment](https://github.com/sdroege/tokio-udp-receiver-benchmark/pull/1#issuecomment-563252013).

How does it compare in the benchmark in gst-plugin-threadshare with a) 0.2.0-alpha and b) the 0.1 version?

I think it's fine to not have perfect performance for starters as long as it's not much worse than the 0.1 version.

Did you also try running a few pipelines in parallel and checked with some printfs if it actually only schedules/runs things every 20ms (or whatever is configured) instead of waking up in between too? The `RunningDry` case looks like it might wake up earlier. Also if there are more tasks than the constant, you'd not handle them all in one tick but would instead wait and starve them until the next iteration or am I missing something?

But if that's all fine, let's go with that for now :)

The ThrottleState code could probably use some more comments, especially before proposing this upstream.

**Comment by fengalin** [comment]
> The RunningDry case looks like it might wake up earlier.

Indeed, I realized I was trying to remain as close as possible to previous behavior when we had the opportunity to gain finer control. I pushed an update on this in my branch. It's not clean enough yet, I still need to add more comments and  fix stuff.

> Also if there are more tasks than the constant, you'd not handle them all in one tick but would instead wait and starve them until the next iteration or am I missing something?

Actually, the constant is only used to allow polling the main `Future` (the one passed to the `BasicScheduler::block_on` function) and do the tasks cleanup. I tried to stick as close as possible to the structure of the regular `tick` algorithm so that they would be easy to grab and maintain. The constant doesn't change the state machine, so while the state is `ThrottleState::HandlingTasks`, we are handling tasks no matter what (with an occasional pause to poll the main `Future` and perform the cleanup). Only when there are no more tasks to process do we enter `ThrottleState::RanDryOfTasks`, which can lead to a `thread::sleep` if max throttling time is not elapsed since last time timers & IO were polled.

> The ThrottleState code could probably use some more comments, especially before proposing this upstream.

Will do.

I spent some time evaluating and comparing the versions from the migration pass since `tokio-0.1.x`. I also performed some evaluations using the tool from this repository. I pushed a draft of the results [here](https://github.com/fengalin/fengalin-github.io/blob/master/evaluating_throttling_implementations/). I wrote that to help us decide if the throttling algorithm is good enough for a submission upstream and if more actions are required.

**Comment by sdroege** [comment]
> I spent some time evaluating and comparing the versions from the migration pass since `tokio-0.1.x`. I also performed some evaluations using the tool from this repository. I pushed a draft of the results [here](https://github.com/fengalin/fengalin-github.io/blob/master/evaluating_throttling_implementations/). I wrote that to help us decide if the throttling algorithm is good enough for a submission upstream and if more actions are required.

One important part for all these measurements is that the sender is producing data every 20ms, so that should be the optimal throttle time for throughput vs latency. It would probably make sense to have some graphs with that fixed and the number of streams on the X axis, and the CPU usage or the throughput on the Y axis. At least for the intended use-case that's the most important information :)

I'll go through everything else there in more detail later.

**Comment by fengalin** [comment]
> One important part for all these measurements is that the sender is producing data every 20ms

I should probably increase this on my machine because it doesn't seem to be a suitable operating point to demonstrate the benefit of throttling. Initially, I was searching around 20ms, with none of the versions performing well. Will do some more testing tomorrow.

Edit: my comment was about the `threadshare` tests. For the `tokio` only tests, I should have tested around 20ms obviously. :(

**Comment by fengalin** [comment]
I updated [my evaluation](https://github.com/fengalin/fengalin-github.io/tree/master/evaluating_throttling_implementations) for `tokio` + throttling & rebased [the throttling branch](https://github.com/fengalin/tokio/tree/fengalin/throttling) on latest `tokio` `master`. Tell me if you think it's good enough for a submission.

I intend to include a link to the evaluation in the PR in order to support the benefits of the approach. I could remove the `threadshare` results since I couldn't get good results around 20ms. I suspect my machine not to be powerful enough. I would be really glad to be prooved wrong, but couldn't find any other reason after a couple of days...

**Comment by sdroege** [comment]
Ok, I'll take a look and also try the old benchmark on my side :)

**Comment by sdroege** [comment]
btw, `s/bandwidth/throughput/` in the text

**Comment by sdroege** [comment]
> As a consequence, starting the 0.2.2 + throttling benchmark with 4,000 streams and a throttling duration of 50ms takes about 200s for ts-udpsrc.

Shouldn't they all spawn their startup future on the executor at the same time and then on the next single iteration the executor is handling them all at once instead of handling one per iteration (and thus needing 4000 iterations == 200s)?

Was this also the behaviour before already?

> FIXME figure out why the sweet spot is not around 20ms.

For CPU load / throttling, this makes sense. The more you throttle, the lower your CPU load will be.

> The upgrade to tokio-0.2.0.alpha.6 induces a slight increase in CPU load, but quite insignificant when compared to the 10% increase (in relative value) due to the Pad wrapper model as 0.2.0.alpha.6 Pad seems to show. 

This is probably because of new design involves creating a boxed future for each operation, while before that was not necessarily the case? But needs more debugging. 10% seems acceptable though, the design is much easier and more maintainable and we can optimize that later when needed.

----

My own results with tokio-udp-receiver-benchmark from your branch. Did you run with `cargo build --release` btw?
* 1000 ports, normal runtime: 49 throughput, 38% CPU
* 2000 ports, normal runtime: 49 throughput, 76% CPU
* 3000 ports, normal runtime: 49 throughput, 123% CPU
* 1000 ports, 1 group, no throttling: 49 throughput, 12% CPU
* 1000 ports, 1 group, 20ms throttling: 49 throughput, 10% CPU
* 1000 ports, 1 group, 40ms throttling: 49 throughput, 7% CPU
* 2000 ports, 1 group, no throttling: 49 throughput, 24% CPU
* 2000 ports, 1 group, 20ms throttling: 49 throughput, 16% CPU
* 2000 ports, 1 group, 40ms throttling: 49 throughput, 13% CPU
* 3000 ports, 1 group, no throttling: 49 throughput, 37% CPU
* 3000 ports, 1 group, 20ms throttling: 49 throughput, 22% CPU
* 3000 ports, 1 group, 40ms throttling: 49 throughput, 19% CPU
* 1000 ports, 2 group, no throttling: 49 throughput, 12% CPU
* 1000 ports, 2 group, 20ms throttling: 49 throughput, 10% CPU
* 1000 ports, 2 group, 40ms throttling: 49 throughput, 7% CPU
* 2000 ports, 2 group, no throttling: 49 throughput, 24% CPU
* 2000 ports, 2 group, 20ms throttling: 49 throughput, 22% CPU
* 2000 ports, 2 group, 40ms throttling: 49 throughput, 17% CPU
* 3000 ports, 2 group, no throttling: 49 throughput, 40% CPU
* 3000 ports, 2 group, 20ms throttling: 49 throughput, 28% CPU
* 3000 ports, 2 group, 40ms throttling: 49 throughput, 23% CPU

Note that using 40ms throttling here will mean that we'll introduce 40ms latency in addition, instead of 20ms as with 20ms. The throughput is the same, but latency is higher.

Also while with more groups the CPU usage is higher, it allows more parallelization and thus more streams to be handled on the same machine (i.e. you can go to 90% CPU on each group instead of 90% on only one).

So I think that overall confirms your numbers?

Next running the GStreamer-based test for some more numbers.

**Comment by sdroege** [comment]
GStreamer-based benchmark

* 1000 streams, udpsrc: 55% CPU
* 2000 streams, udpsrc: 110% CPU
* git master, 1000 streams, 1 group, no throttling, ts-udpsrc: 44% CPU
* git master, 1000 streams, 1 group, 20ms throttling, ts-udpsrc: 41% CPU
* git master, 2000 streams, 1 group, no throttling, ts-udpsrc: 80% CPU
* git master, 2000 streams, 1 group, 20ms throttling, ts-udpsrc: 72% CPU
* git master, 1000 streams, 2 group, no throttling, ts-udpsrc: 52% CPU
* git master, 1000 streams, 2 group, 20ms throttling, ts-udpsrc: 52% CPU
* git master, 2000 streams, 2 group, no throttling, ts-udpsrc: 105% CPU
* git master, 2000 streams, 2 group, 20ms throttling, ts-udpsrc: 93% CPU
* 0.2 alpha branch, 1000 streams, 1 group, no throttling, ts-udpsrc: 44% CPU
* 0.2 alpha branch, 1000 streams, 1 group, 20ms throttling, ts-udpsrc: 40% CPU
* 0.2 alpha branch, 2000 streams, 1 group, no throttling, ts-udpsrc: 79% CPU
* 0.2 alpha branch, 2000 streams, 1 group, 20ms throttling, ts-udpsrc: 74% CPU
* 0.2 alpha branch, 1000 streams, 2 group, no throttling, ts-udpsrc: 53% CPU
* 0.2 alpha branch, 1000 streams, 2 group, 20ms throttling, ts-udpsrc: 51% CPU
* 0.2 alpha branch, 2000 streams, 2 group, no throttling, ts-udpsrc: 107% CPU
* 0.2 alpha branch, 2000 streams, 2 group, 20ms throttling, ts-udpsrc: 96% CPU
* 0.2.0, 1000 streams, 1 group, no throttling, ts-udpsrc: 43% CPU
* 0.2.0, 1000 streams, 1 group, 20ms throttling, ts-udpsrc: 41% CPU
* 0.2.0, 2000 streams, 1 group, no throttling, ts-udpsrc: 79% CPU
* 0.2.0, 2000 streams, 1 group, 20ms throttling, ts-udpsrc: 74% CPU
* 0.2.0, 1000 streams, 2 group, no throttling, ts-udpsrc: 55% CPU
* 0.2.0, 1000 streams, 2 group, 20ms throttling, ts-udpsrc: 53% CPU
* 0.2.0, 2000 streams, 2 group, no throttling, ts-udpsrc: 105% CPU
* 0.2.0, 2000 streams, 2 group, 20ms throttling, ts-udpsrc: 85% CPU

**Comment by sdroege** [comment]
I think with that the 0.2.0 branch is basically behaving the same as git master and ready performance-wise to be merged or what do you think? There seems to be no performance regression at least.

**Comment by fengalin** [comment]
> Shouldn't they all spawn their startup future on the executor at the same time and then on the next single iteration the executor is handling them all at once instead of handling one per iteration (and thus needing 4000 iterations == 200s)?

I can do that but I thought that the purpose of the `NullToReady` transition was to allocate the resources. So I decided to block until the `UdpSocket` is available. We may also `spawn` the `UdpSocket` without blocking and `join` in the `ReadyToPaused` state for example, this way we would benefit from the I/O grouping. But in case of an error this would be detected in the wrong state AFAICT.

> Was this also the behaviour before already?

No, before tokio-0.2.0, we could pass the I/O reactor during the creation of `UdpSocket` and that could be done on the main thread, so we didn't have to `spawn` and wait. [More details in the analysis](https://github.com/fengalin/fengalin-github.io/tree/e4b003b5264dcd7f4d1cd7f1c58b7c516dca74f2/evaluating_throttling_implementations#notable-consequence-of-the-upgrade-to-tokio-02x).

> For CPU load / throttling, this makes sense. The more you throttle, the lower your CPU load will be.

Sure, my wording is not correct. What I wanted to state is that my tests didn't show an improvement of `ts-udpsrc` over `udpsrc` @ 20ms.

> Did you run with cargo build --release btw?

Sure :):

```
All executables are built before-hand in release version.
```

> Note that using 40ms throttling here will mean that we'll introduce 40ms latency in addition, instead of 20ms as with 20ms. The throughput is the same, but latency is higher.

Yes, I wanted to mention this. Thanks for reminding me. By the way, do you think it's worth including the measurements @40ms?

I'm reassured by your measurements with `threadshare`. Thanks for doing this. I should probably use your results instead of mine (and invest in a better host...), what do you think? Could you give me the details of your machine (like in the form I used [here](https://github.com/fengalin/fengalin-github.io/tree/e4b003b5264dcd7f4d1cd7f1c58b7c516dca74f2/evaluating_throttling_implementations#conditions)) please?

> I think with that the 0.2.0 branch is basically behaving the same as git master and ready performance-wise to be merged or what do you think?

I'll answer this in the related MR thread.

**Comment by sdroege** [comment]
> > Shouldn't they all spawn their startup future on the executor at the same time and then on the next single iteration the executor is handling them all at once instead of handling one per iteration (and thus needing 4000 iterations == 200s)?
> 
> I can do that but I thought that the purpose of the `NullToReady` transition was to allocate the resources. So I decided to block until the `UdpSocket` is available. We may also `spawn` the `UdpSocket` without blocking and `join` in the `ReadyToPaused` state for example, this way we would benefit from the I/O grouping. But in case of an error this would be detected in the wrong state AFAICT.

If it's something that can block for a while it is better to not do it as part of the state transition but later from a streaming thread. See e.g. also `rtspsrc` doing all its network stuff asynchronously. It's fine to error our for these things at a later time if otherwise it means blocking the application.

> > Did you run with cargo build --release btw?
> 
> Sure :):

Ok, just making sure because I got numbers close to your when I first ran it in debug mode :)

> > Note that using 40ms throttling here will mean that we'll introduce 40ms latency in addition, instead of 20ms as with 20ms. The throughput is the same, but latency is higher.
> 
> Yes, I wanted to mention this. Thanks for reminding me. By the way, do you think it's worth including the measurements @40ms?

I think it's still useful to mention. It reduces CPU usage even more at the cost of more latency. That sometimes might be worthwhile doing if you optimize for more streams on the same machine than would otherwise be possible. Then you would at least have the knob that affects the latency further that you can tune to make it possible.

> I'm reassured by your measurements with `threadshare`. Thanks for doing this. I should probably use your results instead of mine (and invest in a better host...), what do you think? Could you give me the details of your machine (like in the form I used [here](https://github.com/fengalin/fengalin-github.io/tree/e4b003b5264dcd7f4d1cd7f1c58b7c516dca74f2/evaluating_throttling_implementations#conditions)) please?

* CPU: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (+ all the microcode updates until a few days ago)
* Kernel: Linux 5.3.9 (Debian unstable)
* Memory: 4x8GB DDR3 at 1600MHz

**Comment by fengalin** [comment]
I updated the [evaluation](https://github.com/fengalin/fengalin-github.io/tree/master/evaluating_throttling_implementations) with your results for threadshare @ 2,000 streams. I though it was not necessary to use the results @ 1,000 streams because they don't show as much a benefit for the throttling strategy.

Could you tell me if you think this is good enough in your opinion to support the PR to `toktio`?

Edit: just added a precision about the `group` parameter in the `threadshare` `benchmark` tool.

**Comment by sdroege** [comment]
> Could you tell me if you think this is good enough in your opinion to support the PR to `tokio`?

I think so, but only one way to find out... :)

Thanks for preparing this!

**Pull request closed without merging**
